base_model = "openai/gpt-oss-120b"
name = "gpt-oss-120b (free)"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["low", "medium", "high"]

[cost]
input = 0
output = 0

[limit]
output = 131_072
